core/api/urls.py
from django.urls import path

from . import views

# app_name = 'core'

urlpatterns = [
    path('', views.TODO.as_view(), name='list-display'),
]

core/urls.py
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('accounts/profile/', views.profile, name='profile'),
    path('signup/', views.signup, name='signup'),

    path('create-list/', views.list_create, name='list-create'),

    path('list-detail/<slug:title>/', views.list_detail, name='list-detail'),
    path('list-detail/<slug:title>/change/', views.list_update, name='list-update'),
    path('list-detail/<slug:title>/delete/', views.list_delete, name='list-delete'),
    path('list-detail/<slug:title>/delete-confirm', views.list_delete_confirm, name='list-delete-confirm'),

    path('list-detail/<slug:title>/create-task/', views.task_create, name='task-create'),
    path('list-detail/<slug:title>/<slug:task>/change', views.task_update, name='task-update'),
    path('list-detail/<slug:title>/<slug:task>/delete/', views.task_delete, name='task-delete'),
    path('list-detail/<slug:title>/<slug:task>/delete-confirm/', views.task_delete_confirm, name='task-delete-confirm'),

    path('search/', views.search_list_or_task, name='search'),

    path('share/<slug:title>/', views.share_list, name='share'),

]

todo/urls.py
# django imports
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api/', include('core.api.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
# django imports
from django.db import models
from django.contrib.auth import get_user_model
from django.utils.text import slugify
from django.urls import reverse

# third-party imports 
import uuid
from datetime import datetime

# local imports
from .choices import *
from .validators import validate_mobile


User = get_user_model()


class CommonFields(models.Model):
    """ Base class for TODOLIST and TODOITEM class. """
    title           =   models.CharField(max_length=50, null=True, unique=True) 
    date_created    =   models.DateTimeField('created', auto_now_add=True, editable=False, blank=True, null=True)
    date_updated    =   models.DateTimeField('updated', auto_now=True, editable=False, blank=True, null=True)
    slug            =   models.SlugField(max_length=100, unique=True, null=True)

    class Meta:
        abstract = True


class Profile(models.Model):
    """ Create profile table for user. """
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    picture = models.FileField('profile picture', upload_to='profile_pictures', null=True, blank=True)
    dob = models.DateField('Date of Birth', null=True, blank=True)
    gender = models.CharField(choices=GENDER, max_length=6, null=True, blank=True)
    mobile = models.CharField(max_length=10, unique=True, null=True, blank=True)
    city = models.CharField(max_length=10, null=True, blank=True)

    def __str__(self):
        return 'profile - %s' %self.user.get_full_name()


class TodoList(CommonFields):
    """ Create todolist table. """
    user      = models.ForeignKey(User, on_delete=models.CASCADE, related_name='lists', null=True)
    is_pinned = models.BooleanField(default=False, null=True) 
    shared_with = models.ManyToManyField(User, related_name='shared_users')

    def get_absolute_url(self):
        return reverse('core:list-detail', kwargs={'title': self.slug})

    def get_list_delete_url(self):
        return reverse('core:list-delete', kwargs={'title': self.slug})

    def get_list_delete_confirm_url(self):
        return reverse('core:list-delete-confirm', kwargs={'title': self.slug})

    def get_list_update_url(self):
        return reverse('core:list-update', kwargs={'title': self.slug})
    
    def __str__(self):
        return self.slug    

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs) 

    class Meta:
        ordering = ['-date_updated']


class TodoItem(CommonFields):
    """ Create todo-item table. """
    td_list         = models.ForeignKey(TodoList, on_delete=models.CASCADE, related_name='list', null=True, blank=True)
    action          = models.CharField(choices=ACTIONS, max_length=50, null=True, default=ACTIONS[0][0])

    def get_task_delete_url(self):
        return reverse('core:task-delete', kwargs={'title': self.td_list.slug, 'task': self.slug})

    def get_task_delete_confirm_url(self):
        return reverse('core:task-delete-confirm', kwargs={'title': self.td_list.slug, 'task': self.slug})

    def get_task_update_url(self):
        return reverse('core:task-update', kwargs={'title': self.td_list.slug, 'task': self.slug})

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.slug   

    class Meta:
        ordering = ['-date_updated']

core/api/views.py
from .serializers import TodoListSerializer
# from rest_framework.views.generic import ListAPIView
from rest_framework.parsers import JSONParser
from rest_framework.response import Response
from rest_framework.views import APIView
from core.models import TodoList
from datetime import date
from django.contrib.auth.models import User


class TODO(APIView):
    def post(self, request, *args, **kwargs):
        data = request.data
        print(data)
        day, month, yr = [int(x) for x  in data.get('date_created').split('-')]
        dt = date(yr, month, day)
        # res = TodoList.objects.filter(user__username=data.get('user')).order_by('-date_created')
        res = TodoList.objects.filter(user__username=data.get('user'), date_created__contains=dt).order_by('-date_created')
        # res = TodoList.objects.filter(date_created=dt).order_by('-date_created')
        print(res)
        seriaizer =  TodoListSerializer(res, many=True)
        return Response({'data': seriaizer.data})
        

core/views.py
# django imports
from django.shortcuts import render, HttpResponseRedirect, reverse, HttpResponse
from django.core.paginator import Paginator
from django.http import HttpResponseNotAllowed
from django.contrib import messages
from django.shortcuts import redirect
from django.utils.text import slugify
from django.db import IntegrityError
from django.db.models import Q
from django.contrib.auth import get_user_model
from django.db import IntegrityError
from django.contrib.auth.decorators import login_required, user_passes_test

# local imports
from .models import *
from .forms import SignupForm, ListForm, TaskForm

# third-party imports
from itertools import chain 

User = get_user_model()


@login_required
def index(request):
    """ Renders lists created by logged in user. ie. homepage """
    context = {}
    context['list'] = TodoList.objects.filter(user=request.user)
    context['shared_list'] = TodoList.objects.filter(shared_with=request.user)
    return render(request, 'core/index.html', context)


# TODO list operations
@login_required
def list_create(request, *args, **kwargs):
    """ Create todo list with provided data and render empty form. """
    context = {}
    if request.method == 'POST':
        form = ListForm(request.POST, user=request.user)
        if form.is_valid():

            obj = form.save(commit=False)
            obj.user = request.user
            obj.save()
            messages.success(request, '"%s" list created'%(obj.title))
            return HttpResponseRedirect(reverse('core:index'))
        else:
            context['form'] = form
            return render(request, 'core/list-create.html', context)
    else:
        context['form'] = ListForm()
        return render(request, 'core/list-create.html', context)
    

@login_required
def list_update(request, *args, **kwargs):
    """ Update todo list. """
    context = {}
    if request.method == 'POST':
        obj = TodoList.objects.get(slug=kwargs.get('title'))
        form = ListForm(request.POST, instance=obj)
        if form.is_valid():
            if form.has_changed():
                obj = form.save(commit=False)
                obj.user = request.user
                obj.save()
                messages.success(request, '"%s" list updated'%(obj.title))
                return HttpResponseRedirect(reverse('core:index'))
            else:
                messages.info(request, 'Nothing has updated')
                return HttpResponseRedirect(reverse('core:index'))
        else:
            context['form'] = form
            return render(request, 'core/list-update.html', context)
    else:
        obj = TodoList.objects.get(slug=kwargs.get('title'), user=request.user)
        context['form'] = ListForm(instance=obj)
        return render(request, 'core/list-update.html', context)



@login_required
def list_detail(request, *args, **kwargs):
    """ Renders todo list details. """
    context = {}
    try:
        obj = TodoList.objects.get(slug=kwargs.get('title'), user=request.user)
        paginator = Paginator(TodoItem.objects.filter(td_list=obj), 2)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        context['object'] = obj
        context['tasks'] = page_obj
        return render(request, 'core/list-detail.html', context)
    except TodoList.DoesNotExist as e:
        return HttpResponseRedirect(reverse('core:index'))
    return render(request, 'core/index.html', context)


@login_required
def list_delete(request, *args, **kwargs):
    """ Prompts user for the deletion of todo list. """
    context = {}
    try:
        obj = TodoList.objects.get(slug=kwargs.get('title'))
        context['object'] = obj
        return render(request, 'core/list-delete-confirm.html', context)
    except TodoList.DoesNotExist as e:
        return HttpResponseRedirect(reverse('core:index'))
    return render(request, 'core/index.html', context)


@login_required
def list_delete_confirm(request, *args, **kwargs):
    """ Delete todo list after confirmation. """
    context = {}
    try:
        obj = TodoList.objects.get(slug=kwargs.get('title'))
        messages.success(request, '"%s" deleted'%(obj.title))
        obj.delete()
        return HttpResponseRedirect(reverse('core:index'))
    except TodoList.DoesNotExist as e:
        return HttpResponseRedirect(reverse('core:list-detail', kwargs={'title': kwargs.get('title')}))


# TODO task operations

@login_required
def task_create(request, *args, **kwargs):
    """ Creates task and add to the list. """
    context = {}
    instance = TodoList.objects.get(slug=kwargs.get('title'))
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.td_list = instance
            obj.save()
            messages.success(request, '"%s" task created'%(obj.title))
            return HttpResponseRedirect(reverse('core:list-detail', kwargs={'title': instance.slug}))
        else:
            context['form'] = form
            context['object'] = instance
            return render(request, 'core/task-create.html', context)
    else:
        context['object'] = instance
        context['form'] = TaskForm()
        return render(request, 'core/task-create.html', context)
    

@login_required
def task_update(request, *args, **kwargs):
    """ Update todo task. """
    context = {}
    instance = TodoList.objects.get(slug=kwargs.get('title'))
    obj = TodoItem.objects.get(slug=kwargs.get('task'))
    if request.method == 'POST':
        form = TaskForm(request.POST, instance=obj)
        if form.is_valid():
            if form.has_changed():
                obj = form.save(commit=False)
                obj.td_list = instance
                obj.save()
                messages.success(request, '"%s" task updated'%(obj.title))
                return HttpResponseRedirect(reverse('core:list-detail', kwargs={'title': instance.slug}))
            else:
                messages.info(request, 'Nothing has updated')
                return HttpResponseRedirect(reverse('core:list-detail', kwargs={'title': instance.slug}))
        else:
            context['form'] = form
            context['object'] = instance
            context['task'] = obj
            return render(request, 'core/task-update.html', context)
    else:
        context['object'] = instance
        context['task'] = obj
        context['form'] = TaskForm(instance=obj)
        return render(request, 'core/task-update.html', context)
    

@login_required
def task_delete(request, *args, **kwargs):
    """ Prompts user for the deletion of todo task. """
    context = {}
    try:
        obj = TodoList.objects.get(slug=kwargs.get('title'))
        task = TodoItem.objects.get(slug=kwargs.get('task'))
        context['object'] = obj
        context['task'] = task
        return render(request, 'core/task-delete-confirm.html', context)
    except TodoList.DoesNotExist as e:
        return HttpResponseRedirect(reverse('core:index'))
    return render(request, 'core/index.html', context)


@login_required
def task_delete_confirm(request, *args, **kwargs):
    """ Delete todo task after confirmation. """
    context = {}
    try:
        obj = TodoItem.objects.get(slug=kwargs.get('task'))
        messages.success(request, '"%s" deleted'%(obj.title))
        obj.delete()
        return HttpResponseRedirect(reverse('core:list-detail', kwargs={'title': kwargs.get('title')}))
    except TodoList.DoesNotExist as e:
        return HttpResponseRedirect(reverse('core:list-detail', kwargs={'title': kwargs.get('title')}))


@login_required
def profile(request, *args, **kwargs):
    """ Display details of logged in user. """
    context = {}
    return render(request, 'registration/profile.html', context)


def signup(request, *args, **kwargs):
    """ Render signup form and create user and profile object. """
    context = {}
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            user = User.objects.create_user(
                username=data.get('username'), 
                password=data.get('password1'),
                email=data.get('email'),
                first_name=data.get('first_name'),
                last_name=data.get('last_name')
            )
            profile = Profile.objects.get(user=user)
            profile.mobile = data.get('mobile')
            profile.city = data.get('city')
            profile.gender = data.get('gender')
            profile.dob = data.get('dob')
            profile.save()
            messages.success(request, 'You have successfully signed up')
            return HttpResponseRedirect(reverse('login'))
        else:
            context['form'] = form
            return render(request, 'registration/signup.html', context)            
    else:        
        context['form'] = SignupForm()
        return render(request, 'registration/signup.html', context)

def search_list_or_task(request, *args, **kwargs):
    context = {}
    q = request.GET.get('query').strip()
    if q:
        if TodoList.objects.filter(Q(user=request.user, title__iexact=q)).exists():
            obj = TodoList.objects.get(user=request.user, title__iexact=q)
            return HttpResponseRedirect(reverse('core:list-detail', kwargs={'title': obj.slug}))
        else:   
            lists = TodoList.objects.filter(
                    Q(user=request.user) &
                    Q(title__icontains=q)
                ).distinct()
            tasks = TodoItem.objects.filter(
                    Q(td_list__user=request.user) &
                    Q(title__icontains=q)
                ).distinct()
            context['results'] = list(chain(lists, tasks))
            return render(request, 'core/search-results.html', context)
    else:
        return render(request, 'core/search-results.html', context)

core/templates/core/list-create.html
{% extends 'base.html' %}
{% load icons %}
{% load crispy_forms_tags %}

{% block title %} Create list {% endblock title %}

{% block body %}
    <div class="d-flex justify-content-start">
        <div class="card" style="width: 25rem">
            <div class="card-header text-center">
                Create list
            </div>
            <div class="card-body">
                <form method="POST" action="{{ request.path }}">
                    {% csrf_token %}
                    {% crispy form %}
                </form> 
            </div>
        </div>
    </div>
{% endblock body %}

core/templates/core/list-detail.html
{% extends 'base.html' %}
{% load icons %}

{% block breadcrumb %}
    <li class="breadcrumb-item active" aria-current="page">{{ object.title|title }}</li>
{% endblock breadcrumb %}

{% block title %}
    {{ object.title|title }}
{% endblock title %}

{% block body %}
    <div class="card">
        <div class="card-header">
            <div class="d-flex justify-content-between align-items-center">
                <div>
                    {% if object.is_pinned %}
                        {% icon 'thumb-tack' extra_classes='pr-2' %} 
                    {% endif %}
                    {{ object.title|capfirst }}
                </div>
                <div class="btn-group btn-group-sm" role="group" aria-label="Basic mixed styles example">
                    <a class="btn btn-light mr-1 btn-outline-primary rounded-0" href="{% url 'core:task-create' object.slug %}">{% icon 'plus' title='Add task' %} Add a task</a>
                    <a class="btn btn-primary rounded-circle mr-1" href="{{ object.get_list_update_url }}">{% icon 'edit (alias)' title='Edit' %}</a>
                    <a class="btn btn-danger rounded-circle mr-1" href="{{ object.get_list_delete_url }}">{% icon 'trash' title='Delete' %}</a>
                </div>       
            </div>
        </div>
        <div class="card-body p-0">
            {% if object.list.count %}
            <table class="table mb-0 table-borderless table-hover">
                <thead>
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">Title</th>
                    <th scope="col">Status</th>
                    <th scope="col">Created</th>
                    <th scope="col">Updated</th>
                    <th scope="col">Actions</th>
                  </tr>
                </thead>
                <tbody>
                    {% for item in object.list.all %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ item.title|capfirst }}</td>
                        <td>
                            <span class="text-light badge 
                            {% if item.action == 'pending' %} bg-secondary
                            {% elif item.action == 'on-going' %} bg-warning
                            {% elif item.action == 'completed' %} bg-success
                            {% endif %}
                            ">{{ item.action|title }}</span>
                        </td>
                        <td>{{ item.date_created|timesince }} ago</td>
                        <td>{{ item.date_updated|timesince }} ago</td>
                        <td>
                            <div class="btn-group btn-group-sm" role="group" aria-label="Basic mixed styles example">
                                <a class="btn btn-outline-success" href="{{ item.get_task_update_url }}">{% icon 'edit (alias)' title='Edit' %}</a>
                                <a class="btn btn-outline-danger" href="{{ item.get_task_delete_url }}">{% icon 'remove' title='Delete' %}</a>
                            </div>   
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% else %}
                <div>
                    <small id="emailHelp" class="form-text text-muted">- Empty list</small>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock body %}

core/templates/core/list-share.html
{% extends 'base.html' %}
{% load icons %}

{% block breadcrumb %}
    <li class="breadcrumb-item active" aria-current="page">{{ object.title|title }}</li>
{% endblock breadcrumb %}

{% block title %}
    {{ object.title|title }} Share
{% endblock title %}

{% block body %}
    <div class="card">
        <!-- <div class="card-header"> -->
            <!-- <div class="d-flex justify-content-between align-items-center">
                <div>
                    {% if object.is_pinned %}
                        {% icon 'thumb-tack' extra_classes='pr-2' %} 
                    {% endif %}
                    {{ object.title|capfirst }}
                </div>
                <div class="btn-group btn-group-sm" role="group" aria-label="Basic mixed styles example">
                    <a class="btn btn-outline-info ml-1" href="{{ object.get_list_delete_url }}">Share</a>
                    <a class="btn btn-light ml-1 btn-outline-primary rounded-0" href="{% url 'core:task-create' object.slug %}">{% icon 'plus' title='Add task' %} Add a task</a>
                    <a class="btn btn-primary rounded-circle ml-1" href="{{ object.get_list_update_url }}">{% icon 'edit (alias)' title='Edit' %}</a>
                    <a class="btn btn-danger rounded-circle ml-1" href="{{ object.get_list_delete_url }}">{% icon 'trash' title='Delete' %}</a>
                </div>       
            </div> -->
        <!-- </div> -->
        <!-- <div class="card-body p-0">
            {% if object.list.count %}
            <table class="table mb-0 table-borderless table-hover">
                <thead>
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">Title</th>
                    <th scope="col">Status</th>
                    <th scope="col">Created</th>
                    <th scope="col">Updated</th>
                    <th scope="col">Actions</th>
                  </tr>
                </thead>
                <tbody>
                    {% for item in tasks %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ item.title|capfirst }}</td>
                        <td>
                            <span class="text-light badge 
                            {% if item.action == 'pending' %} bg-secondary
                            {% elif item.action == 'on-going' %} bg-warning
                            {% elif item.action == 'completed' %} bg-success
                            {% endif %}
                            ">{{ item.action|title }}</span>
                        </td>
                        <td>{{ item.date_created|timesince }} ago</td>
                        <td>{{ item.date_updated|timesince }} ago</td>
                        <td>
                            <div class="btn-group btn-group-sm" role="group" aria-label="Basic mixed styles example">
                                <a class="btn btn-outline-dark" href="{{ item.get_task_update_url }}">{% icon 'edit (alias)' title='Edit' %}</a>
                                <a class="btn btn-outline-dark" href="{{ item.get_task_delete_url }}">{% icon 'remove' title='Delete' %}</a>
                            </div>   
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% else %}
                <div>
                    <small id="emailHelp" class="form-text text-muted">- Empty list</small>
                </div>
            {% endif %}
            <div class="mt-2">
            <nav aria-label="Page navigation example">
                <ul class="pagination pagination-sm justify-content-center">
                    {% if tasks.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page=1">&laquo;</a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="?page={{ tasks.previous_page_number }}" tabindex="-1" aria-disabled="true">Prev</a>
                        </li>
                    {% endif %}

                    <li class="page-item active"><a class="page-link" href="#">{{ tasks.number }}</a></li>
                    {% if tasks.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ tasks.next_page_number }}" tabindex="-1" aria-disabled="true">Next</a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="?page={{ tasks.paginator.num_pages }}">&raquo;</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </div> -->
        <div class="card">
            <div class="card-header">
              Share {{ object.title|capfirst }}
            </div>
            <div class="card-body">
                <form method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="exampleFormControlSelect2">Select the users</label>
                        <select multiple name="users" class="form-control" id="exampleFormControlSelect2">
                          {% for user in users %}
                              <option value="{{ user.username }}">{{ user.get_full_name|title }}</option>
                          {% endfor %}
                        </select>
                      </div>
                      <input type="submit" class="w-100 btn btn-primary" value="Share"/>
                </form>
            </div>
          </div>
        
        </div>
    </div>
{% endblock body %}

core/templates/core/list-update.html
{% extends 'base.html' %}
{% load icons %}
{% load crispy_forms_tags %}

{% block title %} {{ object.title|capfirst }} update {% endblock title %}

{% block body %}
    <div class="d-flex justify-content-start">
        <div class="card" style="width: 25rem">
            <div class="card-header text-center">
                Update list
            </div>
            <div class="card-body">
                <form method="POST" action="{{ request.path }}">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <input class="btn btn-primary w-100" type="submit" value="Save changes">
                </form> 
            </div>
        </div>
    </div>
{% endblock body %}

core/templates/core/task-create.html
{% extends 'base.html' %}
{% load icons %}
{% load crispy_forms_tags %}

{% block title %} Create task {% endblock title %}

{% block body %}
    <div class="d-flex justify-content-start">
        <div class="card" style="width: 22rem;">
            <h5 class="card-header text-center">Create task</h5>
            <div class="card-body">
                <form method="POST" action="{% url 'core:task-create' object.slug %}">
                    {% csrf_token %}
                    {% crispy form %}
                    <!-- <div class="form-group">
                        <input type="text" name="task-title" {% if task_title %}value="{{ task_title }}"{% endif %} required class="form-control" placeholder="Task title" aria-label="Task title" aria-describedby="basic-addon2">
                    </div>
                    <div class="form-group">
                        <select name="action" class="form-control" id="exampleFormControlSelect1">
                            <option value="pending" selected>Pending</option>
                            <option value="on-going">On-going</option>
                            <option value="completed">Completed</option>
                        </select>
                    </div>
                    <button type="submit" class="btn btn-primary">Create task</button>                 -->
                </form>                      
            </div>
          </div>
            
    </div>
{% endblock body %}

core/templates/core/tasks.html
{% extends 'base.html' %}
{% load icons %}

{% block body %}
    <div class="row g-2 my-2">
        <div class="col-sm">
            <button class="btn btn-primary rounded-circle" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
                
            </button>
            
            <div class="collapse mt-2" id="collapseExample">
                <form method="POST" action="{% url 'core:list-create' %}">
                    {% csrf_token %}
                    <div class="form-group">
                      <label for="exampleInputEmail1">List title</label>
                      <input type="text" minlength="3" maxlength="50" name="list-title" value="{{ object.title }}" required class="form-control" aria-describedby="basic-addon2">
                      <small id="emailHelp" class="form-text text-muted">Title should not be greater than 50 characters in length.</small>
                    </div>
                    <div class="form-group form-check">
                      <input type="checkbox" name="is_pinned" {% if object.is_pinned %} checked "{% endif %} class="form-check-input" id="exampleCheck1">
                      <label class="form-check-label" for="exampleCheck1">Pin to homepage</label>
                    </div>
                    <button type="submit" class="btn btn-primary">Create {% icon 'check' %}</button>
                </form>            
              </div>
        </div>
    </div>
    <!-- <div class="row"> -->
        {% for each in list %}
        <!-- <div class="col-md-6 col-sm-6 col-lg-4 col-xl-3"> -->
            <div class="card pull-left m-2" style="width: 20rem;">
                <div class="card-header">
                    {% if each.is_pinned %}
                        {% icon 'thumb-tack' title='Pinned' extra_classes='pr-2' %} {{ object.title|title }}
                    {% endif %}
                    <a href="{{ each.get_absolute_url }}">{{ each.title|capfirst }}</a>
                </div>
                <div class="card-body p-0">
                    <ul class="list-group list-group-flush">
                    {% for item in each.list.all|slice:":2" %}
                        <li class="list-group-item">
                            {{ item.title|title }}
                            <span class="badge 
                            {% if item.action == 'pending' %} bg-secondary
                            {% elif item.action == 'on-going' %} bg-warning
                            {% elif item.action == 'completed' %} bg-success
                            {% endif %}
                            ">{{ item.action|title }}</span>
                        </li>
                    {% empty %}
                    <li class="list-group-item">
                        <small id="emailHelp" class="form-text text-muted">- Empty list</small>
                    </li>
                </li>                    
                    {% endfor %}
                    {% if each.list.count > 2 %}
                    <li class="list-group-item">
                        <a href="{{ each.get_absolute_url }}">More ...</a>
                    </li>
                    {% endif %}
                </ul>
                </div>
            </div>
            <!-- <hr> -->
        <!-- </div> -->
        {% endfor %}
    <!-- </div> -->
    <div class="row">
        
    </div>
{% endblock body %}