core/urls.py
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('accounts/profile/', views.profile, name='profile'),
    path('signup/', views.signup, name='signup'),

    path('create-list/', views.list_create, name='list-create'),

    path('list-detail/<slug:title>/', views.list_detail, name='list-detail'),
    path('list-detail/<slug:title>/change/', views.list_update, name='list-update'),
    path('list-detail/<slug:title>/delete/', views.list_delete, name='list-delete'),
    path('list-detail/<slug:title>/delete-confirm', views.list_delete_confirm, name='list-delete-confirm'),

    path('list-detail/<slug:title>/create-task/', views.task_create, name='task-create'),
    path('list-detail/<slug:title>/<slug:task>/change', views.task_update, name='task-update'),
    path('list-detail/<slug:title>/<slug:task>/delete/', views.task_delete, name='task-delete'),
    path('list-detail/<slug:title>/<slug:task>/delete-confirm/', views.task_delete_confirm, name='task-delete-confirm'),

    path('search/', views.search_list_or_task, name='search'),

    path('share/<slug:title>/', views.share_list, name='share'),

]

todo/urls.py
# django imports
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api/', include('core.api.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
{% load icons %}
{% load crispy_forms_tags %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Google fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Lobster+Two&display=swap" rel="stylesheet">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

    <!-- Local CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>
      TO-DO - {% block title %} App {% endblock title %}
    </title>
  </head>
  <body>

    <!-- Container starts -->
    <div class="container-fluid px-0">

      <!-- Navbar starts -->
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        
        <!-- Branding starts -->
        <a class="navbar-brand" href="{% url 'core:index' %}">
          {% icon 'tasks' extra_classes='fa-flip-horizontal' %} 
          TODO
        </a>
        <!-- Branding ends -->
        
        <!-- Navbar toggler starts -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#todoNavbar" aria-controls="todoNavbar" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <!-- Navbar toggler ends -->

        <!-- Collapsable nav starts -->
        <div class="collapse navbar-collapse" id="todoNavbar">

          <!-- Navigation items starts -->
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'core:index' %}">{% icon 'home' extra_classes='fa-lg' %} <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {% if user.profile.picture %}
                  <img src="{{ user.profile.picture.url }}" alt="..." class="rounded-circle" style="width:25px; height:25px">
                  {% else %}
                    {% icon 'user-circle-o' extra_classes='fa-lg' %}
                {% endif %}
              </a>
              <div class="dropdown-menu mt-2">
                <h6 class="dropdown-header p-0 text-center">
                  {% if user %}
                    {{ user.get_full_name|title }}
                  {% endif %}
                </h6>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'core:profile' %}">{% icon 'user (profile)' %} My profile</a>
                <a class="dropdown-item" href="{% url 'password_change' %}">{% icon 'cogs (settings)' %} Change password</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'logout' %}">{% icon 'sign-out' %} Logout</a>
              </div>
            </li>
          </ul>
          <!-- Navigation items starts -->
          
          <!-- Create list starts -->
          <a class="btn text-light btn-link btn-outline-success mr-3 rounded-circle" href="{% url 'core:list-create' %}" role="button">
            {% icon 'plus' title='Add list' %} 
          </a>
          <!-- Create list ends -->

          <!-- Search form starts -->
          <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'core:search' %}">
            <input class="form-control mr-sm-2" maxlength="20" name="query" required type="search" placeholder="Search" aria-label="Search">
            <!-- No implementation of button to submit form because of search field -->
            </div>
          </form>
          <!-- Search form ends -->

        </div>
        <!-- Collapsable nav ends -->

      </nav>
      <!-- Navbar ends -->
    </div>

    <div class="container">
      {% for message in messages %}
        <!-- System message info starts -->
        <div class="text-center mx-2 alert alert-{% if message.tags == 'error' %}danger{% else %}{{message.tags}}{% endif %}
            alert-dismissible fade show mt-1" role="alert">
          <strong>{{ message.tags|capfirst }} : </strong> {{ message|capfirst }} 
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <!-- System message info ends -->
      {% empty %}
      <!-- If no messages are available -->
      {% endfor %}

      <!-- Banner starts -->
      <div class="row m-1">

        <!-- Left sidebar starts -->
        <div class="col-sm-6 col-md-3 col-lg-3 p-0">

          <!-- Wrapper left sidebar starts -->
          <div class="m-1">
            <div class="list-group">
              <a href="#" class="list-group-item d-flex justify-content-between align-items-center list-group-item-action">
                Tasks 
                <span class="badge bg-primary ml-2 text-light badge-pill">{{ user.lists.count }}</span>
              </a>
              <a href="#" class="list-group-item d-flex justify-content-between align-items-center list-group-item-action">
                Notes
                <span class="badge bg-primary text-light badge-pill">{{ user.lists.count }}</span>
              </a>
            </div>
          </div>
          <!-- Wrapper left sidebar ends -->

        </div>
        <!-- Left sidebar ends -->

        <!-- Main content starts -->
        <div class="col p-0">
          
          <!-- Wrapper main content starts -->
          <div class="m-1">
            {% block body %}{% endblock body %}  
          </div>
          <!-- Wrapper main content ends -->

        </div>
        <!-- Main content ends -->

      </div>
      <!-- Banner ends -->

    </div>
    <!-- Container ends -->
    
    <!-- Scripts starts -->
    <!-- Separate jQuery, Popper and Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
    <!-- Scripts ends -->

  </body>
</html>